alter table signal_layer.roots_offerings
  add column if not exists source_url text,
  add column if not exists source_checked_at date;

with methods(id, approach, source_url) as (
  values
    -- Planning
    ('planning_marketing_audit', 'Bestandsaufnahme von Strategie, Maßnahmen, Organisation, Prozessen und KPIs; Auswertung vorhandener Daten und Stakeholder-Sichten; Verdichtung der Lücken zu priorisierten Handlungsfeldern und einer belastbaren Agenda.', 'https://www.roots-consultants.com/planning/marketing-audit/'),
    ('planning_markt_wettbewerbsanalyse', 'Kundenbedürfnisse, Markttrends, Segmente und Wettbewerber werden strukturiert untersucht; Chancen und Risiken werden bewertet und in differenzierende Wachstumsfelder und Entscheidungsgrundlagen übersetzt.', 'https://www.roots-consultants.com/planning/'),
    ('planning_ideation_workshops', 'Auf Basis von Audit, Zielbild und Kundenproblemen moderiert ROOTS strategisch-kreative Workshops, entwickelt gemeinsam Optionen und bewertet sowie priorisiert die Ideen nach Kundenwert, Machbarkeit und Wachstumspotenzial.', 'https://www.roots-consultants.com/planning/'),
    ('planning_wachstumsstrategie', 'ROOTS bewertet Optionen wie Marktdurchdringung, Marktentwicklung, Produktentwicklung und Diversifikation, priorisiert Initiativen und überführt sie in einen umsetzbaren Wachstumspfad mit Zielen und Roadmap.', 'https://www.roots-consultants.com/planning/'),
    ('planning_innovationsstrategie', 'ROOTS definiert strategische Suchfelder, Entscheidungs- und Bewertungskriterien, Innovationsprozess und Governance; priorisierte Chancen werden anschließend in eine Innovationspipeline und Roadmap überführt.', 'https://www.roots-consultants.com/planning/'),
    ('planning_markenstrategie', 'Markt, Zielgruppen, Wettbewerb und vorhandene Markenstärke werden analysiert; daraus entwickelt ROOTS Zielbild, Positionierung, Markenlogik, Botschaften, Kanäle und einen langfristigen Wachstumsplan für die Marke.', 'https://www.roots-consultants.com/planning/markenstrategie/'),
    ('planning_marketingstrategie', 'ROOTS verbindet Geschäftsziele, Zielkunden, Angebot und Wettbewerb, priorisiert die großen Marketinghebel und definiert Stoßrichtungen, Kanäle, Ressourcen und Messgrößen für einen umsetzbaren Marketingrahmen.', 'https://www.roots-consultants.com/planning/'),
    ('planning_go_to_market_strategie', 'ROOTS strukturiert Zielsegmente, Leistungsversprechen oder Markenpositionierung, Preis, Vertriebswege und Kommunikation und verdichtet diese Bausteine zu einem abgestimmten Launch- und Rolloutplan.', 'https://www.roots-consultants.com/planning/'),
    ('planning_integrierte_marketingplanung', 'Die Marketingstrategie wird horizontal und vertikal in Ziele, Zielgruppen, Maßnahmen, Kanäle, Budgets, Timing und Verantwortlichkeiten übersetzt; ROOTS optimiert dabei Marketing-Mix und Ressourceneinsatz.', 'https://www.roots-consultants.com/planning/'),
    ('planning_markenarchitektur', 'ROOTS inventarisiert das Markenportfolio, klärt Rollen und Beziehungen von Dach-, Sub- und Produktmarken, bewertet Überschneidungen und Synergien und entwickelt Architekturprinzipien sowie einen Migrationspfad.', 'https://www.roots-consultants.com/planning/markenarchitektur/'),

    -- Purpose
    ('purpose_brand_audit', 'ROOTS wertet Strategiedokumente, Markenstudien, Trackings, Markt- und Kundendaten sowie interne Stakeholder-Sichten aus und verdichtet Wahrnehmung, Wettbewerbsposition und Konsistenz zu konkreten Markenhebeln.', 'https://www.roots-consultants.com/purpose/'),
    ('purpose_markenpositionierung', 'Aus Herkunft, Markt und Wettbewerb, Zielgruppe, Insight, funktionalem und emotionalem Nutzen, Reasons-to-Believe, Werten und Markencharakter entwickelt ROOTS eine differenzierende Positionierung und verdichtet sie in einem anschlussfähigen Modell.', 'https://www.roots-consultants.com/purpose/markenpositionierung/'),
    ('purpose_brand_purpose', 'ROOTS analysiert Herkunft, Überzeugungen, Stärken sowie den relevanten gesellschaftlichen oder kundenseitigen Beitrag und formuliert daraus einen glaubwürdigen Purpose, der Strategie und Handeln orientiert.', 'https://www.roots-consultants.com/purpose/brand-purpose/'),
    ('purpose_value_proposition', 'ROOTS strukturiert Zielgruppe, Problem oder Aufgabe, funktionalen und emotionalen Nutzen, Differenzierung und Belege und formuliert daraus ein klares, entscheidungsrelevantes Leistungs- und Nutzenversprechen.', 'https://www.roots-consultants.com/purpose/value-proposition/'),
    ('purpose_employer_value_proposition', 'Mitarbeiter- und Bewerberbedürfnisse, Kultur, Stärken und Wettbewerbsumfeld werden analysiert; daraus entwickelt ROOTS ein differenzierendes Arbeitgeberversprechen samt Belegen und Leitplanken für Umsetzung und Kommunikation.', 'https://www.roots-consultants.com/purpose/'),
    ('purpose_internal_branding', 'ROOTS übersetzt die Positionierung in Touchpoint-Vision und Brand Principles, bindet Führung und Mitarbeitende ein und verankert Marke und Werte durch Kommunikation, Formate, Verhalten und konkrete interne Markenerlebnisse.', 'https://www.roots-consultants.com/purpose/internal-branding/'),
    ('purpose_handelsmarkenstrategie', 'ROOTS analysiert Kategorie, Shopper, Wettbewerb, Preis- und Qualitätssegmente sowie das bestehende Portfolio; anschließend werden Rolle, Architektur, Positionierung, Value Proposition, Sortimentswirkung und Wachstumslogik der Handelsmarken definiert.', 'https://www.roots-consultants.com/purpose/handelsmarke/'),

    -- Presence
    ('presence_customer_experience_management', 'ROOTS analysiert die bestehende CX-Strategie und relevante Touchpoints, definiert Zielbild und Optimierungspotenziale und priorisiert einen Maßnahmenplan für ein konsistentes, integriertes Kundenerlebnis.', 'https://www.roots-consultants.com/presence/'),
    ('presence_customer_insights', 'Quantitative Daten, Kaufverhalten, Feedback und qualitative Forschung werden verbunden; ROOTS verdichtet Bedürfnisse, Motive und Barrieren zu belastbaren Insights und bei Bedarf zu Buyer Personas und Handlungsfeldern.', 'https://www.roots-consultants.com/presence/customer-insights/'),
    ('presence_customer_journey_maps', 'ROOTS definiert Personas und Aufgaben, erfasst Phasen, Touchpoints, Aktionen, Emotionen, Gains und Pains und visualisiert sie in Journey Maps; daraus werden konkrete Chancen und Verbesserungsmaßnahmen priorisiert.', 'https://www.roots-consultants.com/presence/customer-journey/'),
    ('presence_content_strategie', 'ROOTS verbindet Unternehmens- und Content-Ziele, Zielgruppen und Insights, prüft vorhandene Assets und definiert Themen, Formate, Kanäle, Style, Redaktionsplanung, Prozesse und KPIs für die Umsetzung.', 'https://www.roots-consultants.com/presence/content-marketing-strategie/'),
    ('presence_social_media_strategie', 'ROOTS klärt Ziele und Plattformrollen, analysiert Zielgruppen und bisherigen Content und entwickelt Themen, Formate, Kanal- und Community-Logik, Governance, Planung und messbare KPIs.', 'https://www.roots-consultants.com/presence/social-media-strategie/'),
    ('presence_influencer_marketing_strategie', 'ROOTS definiert Ziele und Rollen von Creator-Kooperationen, strukturiert Auswahl, Briefing, Inhalte, Vergütung, Freigaben und Governance und entwickelt eine Messlogik von Markenwirkung bis Abverkauf.', 'https://www.roots-consultants.com/presence/'),

    -- People
    ('people_marketing_academy', 'ROOTS erhebt Zielgruppen und Kompetenzlücken, entwickelt ein unternehmens- und branchenspezifisches Kompetenzmodell, Curriculum, Lernpfade und Formate und verankert Transfer, Anwendung und Erfolgsmessung in der täglichen Praxis.', 'https://www.roots-consultants.com/people/'),
    ('people_brand_management_grundlagen', 'ROOTS vermittelt und übt die zentralen Bausteine von Markenpositionierung, Markenstrategie, Führung, Aktivierung, Brand Tracking und Erfolgsmessung anhand der konkreten Marken- und Entscheidungssituationen des Unternehmens.', 'https://www.roots-consultants.com/people/'),
    ('people_marketing_for_non_marketers', 'ROOTS übersetzt Marketingprinzipien, Kundenorientierung, Steuerungslogik und Zusammenarbeit in ein praxisnahes Training für Fach- und Führungskräfte außerhalb des Marketings und arbeitet mit konkreten Unternehmensfällen.', 'https://www.roots-consultants.com/people/'),
    ('people_online_marketing_kompetenz', 'ROOTS strukturiert Owned-, Paid- und Plattformkanäle, vermittelt Kampagnen-, Content-, Daten- und Messlogik und trainiert die zielgerichtete Optimierung digitaler Aktivitäten anhand realer Anwendungsfälle.', 'https://www.roots-consultants.com/people/'),
    ('people_content_marketing', 'Teams erarbeiten mit ROOTS Ziele, Zielgruppen und Insights, Content-Strategie, Formate, Prozesse, Frameworks, Technologien und Messung und übertragen das Gelernte unmittelbar auf eigene Inhalte und Abläufe.', 'https://www.roots-consultants.com/people/'),
    ('people_social_media_marketing', 'ROOTS vermittelt Plattform- und Zielgruppenwahl, Content- und Community-Planung, Kampagnensteuerung, Governance und Erfolgsmessung und überführt die Bausteine in einen praxisnahen Social-Media-Ansatz.', 'https://www.roots-consultants.com/people/'),
    ('people_influencer_marketing', 'ROOTS trainiert Einsatzmöglichkeiten von Brand Building bis Abverkauf sowie Creator-Auswahl, Briefing, Kooperation, Freigaben, Governance und Messung und wendet sie auf individuelle Zielstellungen an.', 'https://www.roots-consultants.com/people/'),
    ('people_agenturen_richtig_briefen', 'ROOTS vermittelt die notwendigen Inhalte eines wirksamen Briefings, strukturiert Ziele, Aufgabe, Zielgruppe, Rahmen, Deliverables und Bewertungskriterien und optimiert den Briefing- und Feedbackprozess.', 'https://www.roots-consultants.com/people/'),
    ('people_effiziente_agentur_pitches', 'ROOTS begleitet von Marktanalyse, Long- und Shortlist über RFI, RFQ, Briefing und Auswahlkriterien bis zu Ausschreibung, Präsentationen, Evaluierung, Entscheidung und sauberem Übergang an die gewählte Agentur.', 'https://www.roots-consultants.com/people/'),
    ('people_erste_100_tage_cmo', 'ROOTS begleitet neue CMOs und Marketingleitungen bei Standortbestimmung, Stakeholder- und Team-Ausrichtung, Fallstricken und Prioritäten und entwickelt daraus einen belastbaren Action Plan für Einstieg und erste 100 Tage.', 'https://www.roots-consultants.com/people/100-tage-fuehrungskraft/'),
    ('people_data_analytics', 'ROOTS identifiziert mit dem Team entscheidungsrelevante Daten und KPIs, vermittelt Strukturierung, Analyse und Visualisierung sowie den sinnvollen Einsatz von Analytics-Tools und übt die Übersetzung in Marketingentscheidungen.', 'https://www.roots-consultants.com/people/'),

    -- Productivity
    ('productivity_marketing_operations_audit', 'ROOTS nimmt Prozesse, Datenlandschaft, Verantwortlichkeiten, Capabilities und Systeme auf, bewertet Reifegrad, Engpässe und Doppelarbeit und priorisiert daraus Effizienz- und Wirksamkeitshebel.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_marketing_operations_ziele', 'Aus Geschäfts- und Marketingzielen definiert ROOTS Ziele und KPIs für Effizienz, Produktivität und Impact, identifiziert Gaps und entwickelt Zielbild, Prioritäten und den zugehörigen Business Case.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_martech_oekosystem', 'ROOTS inventarisiert Tools, Datenflüsse, Integrationen und Use Cases, entwickelt ein zukünftiges MarTech-Zielbild und priorisiert die benötigten Lösungen und Umsetzungsschritte in einer realistischen Roadmap.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_marketing_prozesse', 'ROOTS modelliert relevante End-to-End-Prozesse und Workflows, klärt Rollen, Übergaben, Daten und Systemintegrationen, identifiziert Automatisierungspotenzial und definiert den optimierten Sollprozess.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_martech_anbieter', 'ROOTS übersetzt fachliche und technische Anforderungen in RFI oder RFP, erstellt Long- und Shortlist, bewertet Anbieter und Lösungen und begleitet Auswahl, Verhandlung und anschlussfähige Integration.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_governance_modell', 'ROOTS gestaltet Organisations- und Governance-Strukturen, Rollen, Entscheidungsrechte und Verantwortlichkeiten, definiert benötigte Capabilities, Management-Routinen und Performance-Monitoring – einschließlich Responsible AI.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_project_management_office', 'ROOTS stellt PMO- und bei Bedarf Product-Owner-Leistungen bereit, strukturiert Planung, Prioritäten, Ressourcen, Abhängigkeiten, Risiken und Reporting und begleitet die Verankerung neuer Technologien und Prozesse.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_marketing_automation', 'ROOTS priorisiert geeignete Automatisierungs- und KI-Use-Cases, gestaltet Sollprozesse, Daten, Technologie und Governance und begleitet Pilotierung, Skalierung und Messung von Effizienz, Wirkung und ROI.', 'https://www.roots-consultants.com/productivity/'),
    ('productivity_design_to_print_artwork', 'ROOTS analysiert die Packaging Graphic Chain und ihre Durchlaufzeiten, Fehler, Rollen, Freigaben, Daten, Systeme und Dienstleister und gestaltet einen standardisierten, digitalisierten Sollprozess samt Governance und Umsetzungspfad.', 'https://www.roots-consultants.com/markenberatung/'),

    -- Performance
    ('performance_digital_maturity_assessment', 'ROOTS bewertet Reifegrad und Lücken von Analytics-Strategie, Organisation, Prozessen, Daten, Technologie und Kompetenzen und entwickelt daraus ein abgestimmtes Zielbild und eine priorisierte Transformations-Roadmap.', 'https://www.roots-consultants.com/performance/'),
    ('performance_datenstrategie_exekution', 'ROOTS klärt benötigte Daten und Quellen, Data Management, relevante Insights, Use Cases, Verantwortlichkeiten und Governance und überführt sie in Guidelines, Architektur, Prioritäten und einen Exekutionsplan.', 'https://www.roots-consultants.com/performance/'),
    ('performance_marketing_tool_auswahl', 'ROOTS übersetzt Analytics-Anforderungen in Auswahlkriterien, prüft Full-Stack-BI, Web Analytics, Social Listening, Predictive Analytics und weitere Lösungen und begleitet Bewertung, Auswahl und Integration.', 'https://www.roots-consultants.com/performance/'),
    ('performance_customer_journey_analytics', 'ROOTS verbindet Daten und Identitäten über relevante Touchpoints, definiert Journey-KPIs, analysiert Verhalten, Übergänge und Reibungspunkte und priorisiert daraus konkrete Optimierungshebel.', 'https://www.roots-consultants.com/performance/'),
    ('performance_marketing_performance_management', 'ROOTS übersetzt Ziele in relevante Metriken und Messlogik, klärt Datenbasis, Attribution und Interpretation und etabliert Steuerungsroutinen, mit denen Wirkung und Ressourceneinsatz regelmäßig optimiert werden.', 'https://www.roots-consultants.com/performance/'),
    ('performance_kpi_dashboards_reportings', 'ROOTS wählt entscheidungsrelevante KPIs aus, definiert Datenquellen und Berichtslogik, konzipiert verständliche Dashboards und Reports und verankert Monitoring, Review und Lernen für zukünftige Maßnahmen.', 'https://www.roots-consultants.com/performance/')
)
update signal_layer.roots_offerings as offering
set
  description = regexp_replace(offering.description, '\s+Typisches Vorgehen:.*$', '')
    || ' Typisches Vorgehen: ' || methods.approach,
  source_url = methods.source_url,
  source_checked_at = date '2026-08-04',
  updated_at = now()
from methods
where offering.id = methods.id;
